intuit/QuickBooks-V3-PHP-SDK

- src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php
In Zend FW, if `logger` is not registered, this would throw an exception. Added a check to use Zend logger only if it is actually present
> make sure that Zend logger is actually registered

- src/Core/HttpClients/SyncRestHandler.php
- src/Security/OAuthRequestValidator.php
Remove references to OAUTH constants which causes an error when PHP oauth extension is not loaded
> Remove references to OAUTH constants

- src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php
`bool class_exists ( string $class_name [, bool $autoload = true ] )`. If using composer with custom spl_autoload_register it will be broken
> Breaking custom spl_autoload_register

- src/Core/HttpClients/FaultHandler.php
Currently, the fault handler does not retrieve and make available the element where the validation issue occurred. The element where the issue occurring is critical debugging information. 
`echo "The Intuit Helper message is: IntuitErrorType:{" . $error->getIntuitErrorType() . "} IntuitErrorCode:{" . $error->getIntuitErrorCode() . "} IntuitErrorElement:{" . $error-> getIntuitErrorElement() . "} IntuitErrorMessage:{" . $error->getIntuitErrorMessage() . "} IntuitErrorDetail:{" . $error->getIntuitErrorDetail() . "}";`
> Add error element to faulthandler

- src/Core/HttpClients/GuzzleHttpClient.php
- src/DataService/DataService.php
We should use 'verify' key according to http://docs.guzzlephp.org/en/stable/request-options.html#verify
> fix SSL verification using a custom certificate for GuzzleHttpClient

- src/Core/HttpClients/BaseCurl.php
Added checking if $this->curl === 0 for deserialized curl resource. If a curl resource, or an object containing a curl resource, is serialized and later deserialized, the curl resource will pass the isset() test, but the handle will no longer exist. If the curl resource handle is not available, the resource will return 0. Adding this test will help BaseCurl reset $this->curl as necessary. May want to consider renaming isCurlSet() to isCurlSetAndValid().
> Serialized/Deserialized BaseCurl and curl handle is no longer available.

- src/DataService/Batch.php
We see that in the API a lot of information is given in the detail level, this detail level is not given in the Exception (it is given in the Explorer). We have amended the library to add the detail.
> Add Detail to Exception level for better debugging

- src/Facades/TaxAgency.php
- src/_Samples/TaxAgencyCreation.php
Simple commit, just adding the ability to add a TaxAgency through the Facade. Added an example to go with the code.
> Added TaxAgency as facade

- src/Core/HttpClients/CurlHttpClient.php
Fixes incorrect references to TSL which should be TLS. Probably just a typo error.
Agileware Ref: CIVIQBO-47
> Fixes incorrect references to TSL which should be TLS

- src/DataService/DataService.php
I believe this was the original intent of 3a9ce07be5dc73a6ae816e880a384186335f043a based on the indentation there and the fact that `$tmpXML` is of no use if not defined.
> Avoid undefined variable

- .travis.yml
Travis auto load PHPUnit version that is not compatible with PHP7.1.
Force travis to load a lower version.
> Update travis build.

- src/Core/Http/Serialization/JsonObjectSerializer.php
- src/Utility.Test/JsonObjectSerializerTest.php
The `JsonObjectSerializer->removeNullProperties()` method will no longer remove properties that have values of 0 or 0.0. All other _empty_ values will continue to be removed by this method (null, empty string).
Added a unit test to the `src/Utility.Test/JsonObjectSerializerTest.php` test suite.
Commented out one failing test in the `src/Utility.Test/JsonObjectSerializerTest.php` test suite (**Note**: this test suite does not get run by default when invoking `phpunit` at the top-level of the project.)
Closes #64
> Fix json serialization of zero value keys

- src/Core/Http/Serialization/XmlObjectSerializer.php
- src/DataService/DataService.php
Noticed in my editor that there were some errors in these two files related to namespaces.
In `XmlObjectSerializer` there was no `use` statement for the `QuickBooksOnline\API\Diagnostics\TraceLevel` class, but it's being used as `TraceLevel` in the file, which doesn't exist on the `QuickBooksOnline\API\Core\Http\Serialization` namespace that's defined at the top of the file.
For `DataService` there is an `instanceof` check on a non-global class name that doesn't exist in the namespace defined on the file.  It's actually a redundant check though, as `IPPid` is defined in a `use` statement at the top of the file as `use QuickBooksOnline\API\Data\IPPid;`.
> adding missing use statement, removing invalid if condition check

- .gitignore
- src/Core/HttpClients/BaseCurl.php
- src/Core/HttpClients/CurlHttpClient.php
- src/Core/HttpClients/SyncRestHandler.php
- src/DataService/Batch.php
- src/Exception/IdsException.php
Made several improvements here to sync up with our repo:
1. Removed versionOfTLS() since it was not used anymore - it was already removed in master on your end - this caused issues when doing a lot of requests, howmyssl.com could not handle volume
2. Aligned timeouts, sometimes sandboxes are somewhat slower and the the 10 seconds does not cut it, so I've aligned them to be 100 seconds if they are not actively passed into the function
3. Added the $optionsdata when adding a entity to a batch via AddEntity, this way you can pass in several parameters like allowduplicatedocnum for journals - it was already available in the underlying class just added the var for it
Lastly I've added debug to Batch, our tool is heavily reliant on Batch and we often need to provide Intuit with Intuit TID's, …
> Several improvements for Batch 

- src/DataService/DataService.php
This method expects the file to be sent as a base 64 encoded string.
Redoing encoding causes corrupted file.
Fixes issue #312
> Remove the extra base 64 encode.

- composer.json
This change adds a list of excluded directories to the `archive` section of composer.json, which will prevent those directories from being installed into the vendor directory when installing this SDK as a composer dependency.
This significantly reduces the size of the installed dependency (tested by looking at the resulting .tar file created by the `composer archive` command):
Before: 24,130,560 bytes
After: 6,334,976 bytes
This change, in part, came about as an attempt to remove a file that was causing [composer-require-checker](https://github.com/maglnet/ComposerRequireChecker) to fail when ran on our own project, due to `Parent` being a reserved classname in PHP7. This file was causing it to fail:  src/XSD2PHP/test/data/expected/Xsd2Php/MavenTests/bindings/org/apache/maven/POM/_4_0_0/Pa …
> exclude docs and test dirs in the composer archive config

- src/Core/Http/Serialization/XmlObjectSerializer.php
Need to refer to all reference to a variable with static formatting when you change them to static
> FATAL ERROR FIX

- .gitignore
- src/Core/HttpClients/IntuitResponse.php
`Overview`:
In IntuitResponse.php, a fault response isn't parsed unless the content-type is "application/xml". However, for a 401 response, the content type is "text/xml." This results in the response not being parsed.
It seems like either the check should be updated in IntuitResponse.php::147, or responses should be sent using the content-type of "application/xml".
Fix provided for #351 
Changes:
- `setFaultHandler()` to parse faulty response when the `content-type`:`text/xml`
> Handle faulty response when the response type is text/xml

- src/Data/IPPWrapper.php
This fixes #341 and #329 and should replace the fix in #361 as that change erroneously changes the namespace of the `IPPWrapper` class, but that's not necessary for this fix as all of the IPP SDK classes live in the `QuickBooksOnline\API` namespace as that's how they're autoloaded in `composer.json`.
I didn't see any cases where this class was being explicitly required by filename, but anybody doing that (and not using composer's autoloading) might have an issue loading this class.
A dummy `IPP.php` file that just requires `IPPWrapper.php` could be put in place to combat this situation, if that seems reasonable.
> Renaming file for IPPWrapper class to make it PSR4 and Composer 2 compatible

- src/Core/CoreConstants.php
- src/Data/IPPAccountSubTypeEnum.php
- src/Data/IPPLine.php
- src/Data/IPPMXGlobalInfo.php
- src/Data/IPPTimeActivity.php
- src/Data/IPPTransaction.php
- src/XSD/Finance.xsd
> MinorVersion 68 release

- src/Core/CoreConstants.php
- src/Diagnostics/LoggerBase.php
- src/ReportService/ReportService.php
- src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php
Fix for https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/486 and https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/483
Fix for https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/489
> Fixing Deprecated Warnings for dynamic property
