intuit/QuickBooks-V3-PHP-SDK

src/DataService/DataService.php

This commit does not change behavior, it just unifies formatting across the file, fixes some minor bugs, typos and PHPDoc, so it can be better used as a reference
If this is approved, I will appreciate it (it is easier to work with `DataService` if all code completion actually works correctly), if not, no big deal

code style and PHPDoc fixes

---

src/Facades/Line.php

The Line facade was incorrectly attempting to merge an Account object instead of a Line object.

Added correct merge object for Line

---

.travis.yml

Add PHP 7.1 and 7.2 to travis builds

Add PHP 7.x to travis

---

src/XSD/Finance.xsd
src/XSD/IntuitBaseTypes.xsd
src/XSD/IntuitNamesTypes.xsd
src/XSD/IntuitRestServiceDef.xsd
src/XSD/Report.xsd
src/XSD/SalesTax.xsd
src/XSD2PHP/src/com/mikebevz/xsd2php/PHPClass.php
src/XSD2PHP/src/com/mikebevz/xsd2php/Xsd2Php.php
src/xsd2php.php

Adding the XSD files for Minor Version 23. Modifying xsd2php to support customizations required for QuickBooks PHP SDK. Adding script to quickly generate PHP files from the XSD files.
Refs #143

Customizing XSD2php for Intuit QuickBooks PHP SDK

---

src/ReportService/ReportService.php

Here exception http://prntscr.com/k5z7br
- sizeof should be replaced with strlen. http://php.net/manual/en/function.count.php used for array or \Countable implementation not for string.
- $uriParameterString init value should be empty string not null because you're used append operator.

PHP 7.2 type warning

---

src/Core/HttpClients/CurlHttpClient.php

Need to get around using a * in the Cert Common Name instead of the site name.

cURL SSL Fix

---

docs/_sources/quickstart.rst.txt
docs/quickstart.html

It looks like the comment here was mistakenly copied from the previous code block.  I'm pretty sure the code below it is what you are supposed to do.

Remove confusing, duplicated comment

---

src/DataService/DataService.php

Allow for optional includes like invoiceLink in DataService queries.
Can be used like:
$this->dataService->Query($query, null, null, "invoiceLink");

Update DataService Query() for includes

---

.gitignore
src/Core/CoreConstants.php
src/Data/IPPCreditCardPaymentTxn.php
src/Data/IPPEntityStatusEnum.php
src/DataService/DataService.php
src/DataService/RecurringTransactionAdapter.php
src/Facades/FacadeClassMapper.php
src/XSD/Finance.xsd
src/_Samples/RecurringTransactionCreate.php
src/_Samples/RecurringTransactionDelete.php
src/_Samples/RecurringTransactionRead.php

**Release Candidate:** 
5.4.4  🎉
**Minor Version :** 
54
**Features :** 
- Added support for `Create` and `Delete` operations for `RecurringTransaction` entity.
- Added Samples for `Create` and `Delete` operations  under  [_Samples](https://github.com/intuit/QuickBooks-V3-PHP-SDK/tree/master/src/_Samples)
- Schema update for `MV=54`
**Docs :** 
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/recurringtransaction

Release: v1942 - minorverison=54

---

composer.json

Update `composer.json` with changes.

Composer.json changes 

---

src/DataService/DataService.php
src/_Samples/DownloadPDF.php

Solving for  https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/356

All PDF download as string.

---

src/DataService/DataService.php

``Overview:``
As asked at PR #356 , I've added an option to get the raw PDF instead of write it on disk.

feat: Added an option to get the raw PDF

---

docs/configuration.html
src/Core/Configuration/LocalConfigReader.php
src/Core/OAuth/OAuth2/OAuth2LoginHelper.php
src/Core/ServiceContext.php
src/Diagnostics/LoggerBase.php
src/_Samples/CustomerQuery.php

- Added the ability to enable request logging via configuration for DataService
- Added the ability to control the TraceLevel to log
Closes #330

feat: control logging in dataservice

---

src/Core/CoreConstants.php
src/Data/IPPEmployee.php
src/Data/IPPInvoice.php
src/Data/IPPLine.php
src/Data/IPPNameBase.php
src/Data/IPPReimburseCharge.php
src/Data/IPPReimburseLineDetail.php
src/Data/IPPTransaction.php
src/Data/IPPTxnApprovalInfo.php
src/DataService/DataService.php
src/XSD/Finance.xsd
src/XSD/IntuitNamesTypes.xsd
src/_Samples/DownloadPDF.php
src/_Samples/LinkReimburseChargeToInvoice.php
src/_Samples/ReimburseChargeFindById.php
src/_Samples/ReimburseChargeQuery.php
src/_Samples/SalesReceiptVoid.php
src/xsd2php.php

5.4.4 🎉
57
- Added support for `Read` and `Query` operations for `ReimburseCharge` entity.
- Added Samples for `ReimburseChargeFindById.php` and `ReimburseChargeQuery.php` under [_Samples](https://github.com/intuit/QuickBooks-V3-PHP-SDK/tree/master/src/_Samples)
minorversion=`57`
- #356 Download PDF without writing to disk ( PR : #370 , #360 ) **hacktoberfest** contribution 🚀 
- Setup e2e test ( PR : #369 ) **hacktoberfest** contribution 🚀 
- #330 Request / Response always logging ( PR : #364 ) **hactoberfest** contribution 🚀 
- #357 DataService Void method is not working Sales Receipt 
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/reimbursecharge

Release: v1947 - minorverison=57

---

docs/configuration.html
src/Core/Configuration/LocalConfigReader.php
src/Core/OAuth/OAuth2/OAuth2LoginHelper.php
src/Core/ServiceContext.php
src/Diagnostics/LoggerBase.php
src/_Samples/CustomerQuery.php

`Overview` : 
Reverting the control logging feature in dataService due to bugs reported : #390 
Reverts intuit/QuickBooks-V3-PHP-SDK#364

Revert "feat: control logging in dataservice"

---

src/Core/CoreConstants.php

`Overview`:
New release to address #390

Revert logging functionality

---

src/Core/CoreConstants.php

Release Candidate for :
Minor Version: 65
Changes Added
Minor version updates for mv=65

Release candidate for minor version 65

---

composer.json
composer.lock
phpunit.xml
src/Core/HttpClients/SyncRestHandler.php
src/Core/OAuth/OAuth2/OAuth2LoginHelper.php
test/Core/HttpClients/SyncRestHandlerTest.php
test/Core/OAuth/OAuth2/OAuth2LoginHelperTest.php
test/ServiceContextTest.test.php

- Fix deprecation errors reported in #447 and #448
- Added rudimentary unit tests around files changed
- Update phpunit to address php8 errors when running phpunit
- Minor syntax cleanup

fix: some php8 deprecation errors

---

src/Core/CoreConstants.php
src/Data/IPPEmployee.php
src/Data/IPPTimeActivity.php
src/XSD/Finance.xsd
src/XSD/IntuitNamesTypes.xsd

XSD schema changes for minor version 71

Minor version 71 release may'24

---

src/Core/HttpClients/GuzzleHttpClient.php

function moved to Psr7\Message::toString()
fixes #475 #493

undefined function GuzzleHttp\Psr7\str() - fix #475 #493
